### ISSUE TITLE
Does not detect negative numbers

### ISSUE THREAD

**Issue by pketh** [bjarneo/is-whole-number#1]
to repro: 

```
isWholeNumber = require("is-whole-number")
console.log(isWholeNumber(-1));
```

returns `true` when I'd expect negatives to return `false`: https://www.mathsisfun.com/definitions/whole-number.html

**Comment by pketh** [comment]
see also https://www.mathsisfun.com/whole-numbers.html

**Comment by pketh** [comment]
thx!

**Comment by bjarneo** [comment]
You are: correct. Thank you for submitting this ticket. Will look into it :)

**Comment by bjarneo** [comment]
Updated and released :)

https://github.com/bjarneo/is-whole-number/commit/54d37403fec20f2e612ce4e4540413df220ae0a4
